print("Progress update: Scrape data")
source("scrape_data.R")
print("Progress update: Build database")
source("build_database.R")
print("Progress update: Render dashboard")
rmarkdown::render("ifoa_practising_certificates.Rmd", output_file = "_site/index.html")
