update.packages()
print("Progress update: Install package: modelr")
install.packages("modelr")
print("Progress update: Install package: rmarkdown")
install.packages("rmarkdown")
print("Progress update: Install package: tidyverse")
install.packages("tidyverse")
print("Progress update: Install package: rvest")
install.packages("rvest")
print("Progress update: Install package: httr")
install.packages("httr")
print("Progress update: Install package: readr")
install.packages("readr")
print("Progress update: Install package: purrr")
install.packages("purrr")
print("Progress update: Install package: flexdashboard")
install.packages("flexdashboard")
print("Progress update: Install package: DT")
install.packages("DT")
print("Progress update: Install package: plotly")
install.packages("plotly")

print("Progress update: Scrape data")
source("scrape_data.R")
print("Progress update: Build database")
source("build_database.R")
print("Progress update: Render dashboard")
rmarkdown::render("ifoa_practising_certificates.Rmd", output_file = "_site/ifoa_practising_certificates.html")
