name: automated_updates

# Run daily at 3am
on:
  schedule:
    - cron:  '0 3 * * *'



jobs:
  build_dashboard:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages and run R scripts
        run: |
          PATH=$PATH:/usr/lib/rstudio-server/bin/pandoc
          Rscript build_dashboard_github_actions.R

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add --all
          git commit -am "automated update from github actions: $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions