name: manual_updates

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  update_dashboard:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install renv
        run: |
          install.packages('renv')
        shell: Rscript {0}
      
      - name: Setup renv
        run: |
          renv::activate()
          renv::restore()
        shell: Rscript {0}
      
      - name: Install packages and run R scripts
        run: |
          PATH=$PATH:/usr/lib/rstudio-server/bin/pandoc
          Rscript build_dashboard_github_actions.R
      
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add --all
          git commit -am "automated update from github actions: $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions